services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marketplace-laravel
    volumes:
      - .:/var/www
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db       # Nombre del servicio del contenedor de postgres
      DB_PORT: 5432
      DB_DATABASE: marketplace_db
      DB_USERNAME: admin
      DB_PASSWORD: admin123
    depends_on:
      - db
    networks:
      - marketplace-net
  nginx:
    image: nginx:latest
    container_name: marketplace
   # ports:
       #- "7777:80" #---> despliegue local con puerto 7777
    # Para producci√≥n, comentar ports y usar expose:
    expose:
       - "80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel
    networks:
      - marketplace-net
      - internal-network
      - proxy-network
  db:
    image: postgres:latest
    container_name: marketplace-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: marketplace_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - db-data:/var/lib/postgresql
    networks:
      - marketplace-net

networks:
  marketplace-net:
    driver: bridge
  internal-network:
    external: true
  proxy-network:
    external: true
    
volumes:
  db-data:

